# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='user',
        ),
    ]
